import type { Viewport } from 'next'
import 'primereact/resources/themes/lara-dark-blue/theme.css'
import 'primeicons/primeicons.css'

import './globals.css'
import '../../modules/_index.scss'

import { Providers } from './providers'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

// Avoid prerendering during build (some client-only dependencies rely on runtime).
export const dynamic = 'force-dynamic'

export const viewport: Viewport = {
  colorScheme: 'dark',
  themeColor: '#111827',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="p-dark nuc-next" suppressHydrationWarning>
      <body className="nuc-system nuc-next">
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
