[build]
  command = "pnpm run build"
  publish = ".output/public"

[functions]
  directory = ".netlify/functions"

[build.environment]
  APP_URL = "https://api.nucleify.io"
  API_URL = "https://api.nucleify.io/api"
  NODE_VERSION = "20"
  NETLIFY = "true"
  PNPM_FLAGS = "--shamefully-hoist"
  SSR = "true"

[[redirects]]
  from = "/pl/*"
  to = "/pl/404"
  status = 404

[[redirects]]
  from = "/en/*"
  to = "/en/404"
  status = 404

[[redirects]]
  from = "/*"
  to = "/en/404"
  status = 404
