packages:
  - "."

onlyBuiltDependencies:
  - esbuild
  - "@parcel/watcher"
  - sharp

ignoredBuiltDependencies:
  - workerd

allowedDeprecatedVersions:
  unplugin-vue-router: '*'
  whatwg-encoding: '*'