<template>
  <div id="page-builder-public" style="max-width:100%;margin:0 auto">
    <nuc-section-navbar />
    <nuc-section-faq lang="en" site="home" />
    <nuc-section-footer />
  </div>
</template>

<script setup lang="ts">
// Auto-generated by Page Builder – do not edit manually.
</script>
