// @generated by nucleify-compiler
// editable; rebuild: pnpm compiler -- build --app=solid --force (fixtures/source/button.tsx)
// content-hash: 031fff76ad3b
import './button.css'

type Props = {
  label?: string
}

function onClick() {
  console.log('clicked')
}

export default function Button({ label = 'Click' }: Props) {
  return (
    <button type="button" class="btn" onClick={onClick}>
      {label}
    </button>
  )
}
