// @generated by nucleify-compiler
// editable; rebuild: pnpm compiler -- build --app=solid --force (fixtures/source/counter.tsx)
// content-hash: c6c78df238c6
import { createSignal, createMemo } from 'solid-js'

type Props = {
  label?: string
}

export default function Counter({ label = 'Count' }: Props) {
  const [count, setCount] = createSignal(0)
  const double = createMemo(() => count() * 2)

  function onInc() {
    setCount(count() + 1)
  }

  return (
    <button type="button" onClick={onInc}>
      {label + ': ' + double()}
    </button>
  )
}
