// @generated by nucleify-compiler
// editable; rebuild: pnpm compiler -- build --app=solid --force (fixtures/source/hello.tsx)
// content-hash: 908c641439b0
type Props = {
  title: string
}

export default function Hello({ title }: Props) {
  return <h1 class="hello">{title}</h1>
}
