// @generated by nucleify-compiler
// editable; rebuild: pnpm compiler -- build --app=solid --force (fixtures/source/list.tsx)
// content-hash: 1196d5b6d039
type Props = {
  items: unknown
  showEmpty?: boolean
}

export default function List({ items, showEmpty = true }: Props) {
  return (
    <div class="list">
      {showEmpty ? <p>Empty hint visible</p> : <p>No empty hint</p>}
      <ul>
        {items.map((item, i) => (
          <li key={i}>{item}</li>
        ))}
      </ul>
    </div>
  )
}
