// @generated by nucleify-compiler
// editable; rebuild: pnpm compiler -- build --app=solid --force (fixtures/source/nui_cta.tsx)
// content-hash: 34d5284d8c3a
type Props = {
  label?: string
  disabled?: boolean
  accent?: string
}

function onClick() {
  console.log('nui-cta')
}

export default function NuiCta({
  label = 'Continue',
  disabled = false,
  accent = '#0ea5e9',
}: Props) {
  return (
    <nui-button
      type="button"
      disabled={disabled}
      aria-label={label}
      style={{ color: accent, gap: '0.5rem' }}
      onClick={onClick}
    >
      <nui-icon
        icon="mdi:rocket-launch-outline"
        aria-hidden="true"
        mode="svg"
      />
      {label}
    </nui-button>
  )
}
