export * from './About'
export * from './Admin'
export * from './Auth'
export * from './Blog'
export * from './Dashboard'
export * from './Entity'
export * from './Errors'
export * from './Home'
export * from './Settings'

export * from './register'
