export * from './types'

export { default as ActivityDashboard } from './Activity.vue'
export { default as ArticleDashboard } from './Article.vue'
export { default as ContactDashboard } from './Contact.vue'
export { default as MoneyDashboard } from './Money.vue'
export { default as QuestionDashboard } from './Question.vue'
export { default as LinkDashboard } from './Link.vue'
export { default as TechnologyDashboard } from './Technology.vue'
export { default as UserDashboard } from './User.vue'
