services:
  frontend:
    platform: ${DOCKER_PLATFORM}
    user: "${DOCKER_UID:-1000}:${DOCKER_GID:-1000}"
    build:
      context: ..
      dockerfile: .config/docker/Dockerfile.$APP_FRONTEND
    ports:
      - '3000:3000'
      - '6006:6006'
    volumes:
      - '..:/app'
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - sail
networks:
  sail:
    driver: bridge
