#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npm run check
npm run lint
npm run typeslint
npm run slint
npm run build
npm run storybook:build
npm run test

# ./vendor/bin/pest - I'm testing before commit manually
