#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

export $(grep -v '^#' .env | xargs)

php .pest/guard_check.php

echo 'Pint checking...'
./vendor/bin/pint

npm run check
npm run slint
npm run typeslint
npm run tests
