#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

COMMIT_MSG_FILE="$1"
ORIGINAL_MSG=$(cat "$COMMIT_MSG_FILE")

CURRENT_BRANCH=$(git symbolic-ref --short HEAD)


case "$CURRENT_BRANCH" in
    404)
        FINAL_MSG="404: $ORIGINAL_MSG"
        ;;
    atomic-design)
        FINAL_MSG="⚛ Atomic Design: $ORIGINAL_MSG"
        ;;
    atomic-design-sections)
        FINAL_MSG="⚛ Sections: $ORIGINAL_MSG"
        ;;
    docker)
        FINAL_MSG="🐋 Docker: $ORIGINAL_MSG"
        ;;
    entity-money)
        FINAL_MSG="💵 Money: $ORIGINAL_MSG"
        ;;
    entity-task)
        FINAL_MSG="Task: $ORIGINAL_MSG"
        ;;
    home)
        FINAL_MSG="🏠 Home: $ORIGINAL_MSG"
        ;;
    laravel-meta-tags)
        FINAL_MSG="LaravelMetaTags: $ORIGINAL_MSG"
        ;;
    packages)
        FINAL_MSG="📦 Packages: $ORIGINAL_MSG"
        ;;
    page-about)
        FINAL_MSG="About: $ORIGINAL_MSG"
        ;;
    page-services)
        FINAL_MSG="Services: $ORIGINAL_MSG"
	      ;;
    page-blog)
        FINAL_MSG="Blog: $ORIGINAL_MSG"
	      ;;
    performance)
        FINAL_MSG="⚡ Performance: $ORIGINAL_MSG"
        ;;
    storybook)
        FINAL_MSG="Storybook: $ORIGINAL_MSG"
        ;;
    stylelint)
        FINAL_MSG="Stylelint: $ORIGINAL_MSG"
        ;;
    ui-improvements)
        FINAL_MSG="✨ UI Improvements: $ORIGINAL_MSG"
        ;;
    workflow)
        FINAL_MSG="🛠️ Workflow: $ORIGINAL_MSG"
        ;;
    vitest)
        FINAL_MSG="Vitest: $ORIGINAL_MSG"
        ;;
esac

echo "$FINAL_MSG" > "$COMMIT_MSG_FILE"
