name: ⚙️ Bash

on:
  push:
    branches: ['*']

jobs:
  bash-tests:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run bash test suite
        run: bash .config/bash/tests/run.sh
