import type { Meta, StoryObj } from '@storybook/vue3'

import { AutoComplete as AdAutoComplete } from './'

const meta = {
  title: 'Organisms/AutoComplete',
  component: AdAutoComplete,
  tags: ['autodocs'],
  args: {
    modelValue: {},
    defaultValue: {},
    name: '',
    suggestions: [],
    optionLabel: '',
    optionGroupLabel: '',
    optionGroupChildren: '',
    scrollHeight: '',
    dropdown: false,
    dropdownMode: 'blank',
    multiple: false,
    placeholder: '',
    loading: false,
    size: 'small',
    invalid: false,
    disabled: false,
    variant: 'outlined',
    dataKey: '',
    minLength: 0,
    delay: 0,
    appendTo: '',
    forceSelection: false,
    completeOnFocus: false,
    inputId: '',
    inputStyle: {},
    inputClass: {},
    panelStyle: {},
    panelClass: {},
    overlayStyle: {},
    overlayClass: {},
    dropdownIcon: {},
    dropdownClass: {},
    loader: '',
    removeTokenIcon: '',
    chipIcon: '',
    virtualScrollerOptions: undefined,
    autoOptionFocus: false,
    selectOnFocus: false,
    focusOnHover: false,
    searchLocale: '',
    searchMessage: '',
    selectionMessage: '',
    emptySelectionMessage: '',
    emptySearchMessage: '',
    showEmptyMessage: false,
    tabindex: 0,
    fluid: false,
    ariaLabel: '',
    ariaLabelledby: '',
    formControl: {},
    dt: {},
    pt: {},
    ptOptions: {},
    unstyled: false,
  },
  argTypes: {
    dropdownMode: { control: 'select', options: ['blank', 'current'] },
    size: { control: 'select', options: ['small', 'large'] },
    variant: { control: 'select', options: ['filled', 'outlined'] },
  },
} satisfies Meta<typeof AdAutoComplete>

export default meta
type Story = StoryObj<typeof meta>

export const AutoComplete: Story = {}
